//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteArgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public int DestinoId { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> Dia { get; set; }
    }
}
